packages:
  - "apps/*"
  - "packages/*"
overrides:
  ioredis: 5.11.0
allowBuilds:
  '@nestjs/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: set this to true or false
  sharp: true
